name: main_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  auto_size_text: ^3.0.0
  standard_searchbar: ^2.1.1
  popover: ^0.3.1
  calendar_date_picker2: ^2.0.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.17
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.3.0
  dropdown_model_list: ^2.1.5
  animated_custom_dropdown: ^3.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
