// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChFLVdR5DXs3LijTC82Gzr4edxfOGPE4k',
    appId: '1:1034026899270:web:a8a680082dfb4134fd3747',
    messagingSenderId: '1034026899270',
    projectId: 'hotels-8fe12',
    authDomain: 'hotels-8fe12.firebaseapp.com',
    storageBucket: 'hotels-8fe12.firebasestorage.app',
    measurementId: 'G-JT3MZ35TMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt1ou6qiy_xPXGD-vkD7i8FlOF4hM6zQY',
    appId: '1:1034026899270:android:af35470b5e871ccdfd3747',
    messagingSenderId: '1034026899270',
    projectId: 'hotels-8fe12',
    storageBucket: 'hotels-8fe12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeOsWPNqSCxeaFBXT01qw-W_Aolf6wklc',
    appId: '1:1034026899270:ios:a2e910d116a411c4fd3747',
    messagingSenderId: '1034026899270',
    projectId: 'hotels-8fe12',
    storageBucket: 'hotels-8fe12.firebasestorage.app',
    iosBundleId: 'com.example.mainApp',
  );
}
